sudo: true

language: r

r_packages:
 - VGAM

bioc_packages:
 - Rsamtools
 - GenomicRanges
 - IRanges
 - Biostrings
 - VGAM
 - VariantAnnotation
 - zlibbioc
 - Rhtslib
 
addons:
  apt:
    packages:
    - texlive-fonts-recommended 

